github:
  # baseUrl: https://api.github.com # default
  repos:
    - Kesin11/Firestore-simple
    - Kesin11/github_actions_matrix_js_sandbox
  # exporter:
  #   - local
  #   - bigquery:
  #     dataset: pipeline
  #     table: job
