version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Lint
          command: npm run lint
  build_and_test:
    docker:
      - image: circleci/node:lts
    steps:
      # Setup
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run: npm ci

      # Test
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test:ci -- -w=2
      - run:
          name: Create custom json
          command: |
            OS=$(uname)
            echo "{ \"job\": \"${CIRCLE_JOB}\", \"node\": \"\", \"os\": \"${OS}\", \"container\": \"circleci/node:lts\" }" > custom_report.json

      # Post actions
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
      - store_artifacts:
          path: custom_report.json
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          name: Save npm cache
          paths:
          - ~/.npm
  docker_build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t ci_analyzer .

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - build_and_test:
          requires:
            - lint
  docker:
    jobs:
      - docker_build
