import { round } from "lodash-es";
import { type TestSuites, parse } from "junit2json";
import type { Assign } from "utility-types";
import { z } from "zod";
import type { Artifact } from "../client/client.js";
import type {
  PbWorkflowReport,
  PbWorkflowParams,
} from "../pb_types/workflow.js";
import type {
  PbTestReport,
  PbTestSuites,
  PbTestSuite,
  PbTestCase,
} from "../pb_types/test_report.js";

// Overwrite generated by protobuf types to more strict TypeScript types
export type Status = "SUCCESS" | "FAILURE" | "ABORTED" | "OTHER";
export type WorkflowReport = Assign<
  PbWorkflowReport,
  {
    status: Status;
    successCount: 0 | 1;
  }
>;
export type WorkflowParams = PbWorkflowParams;

// Overwrite generated by protobuf types to more strict TypeScript types
type TestStatus = "SUCCESS" | "FAILURE";
type TestCaseStatus = "SUCCESS" | "FAILURE" | "ERROR" | "SKIPPED";
export type TestReport = Assign<
  PbTestReport,
  {
    successCount: 0 | 1;
    status: TestStatus;
    createdAt: Date;
    testSuites: ReportTestSuites;
  }
>;
export type ReportTestSuites = Assign<
  PbTestSuites,
  {
    testsuite: ReportTestSuite[];
  }
>;
type ReportTestSuite = Assign<
  PbTestSuite,
  {
    testcase: ReportTestCase[];
    timestamp: Date;
  }
>;
type ReportTestCase = Assign<
  PbTestCase,
  {
    successCount: 0 | 1;
    status: TestCaseStatus;
  }
>;

export interface Analyzer {
  createWorkflowParams(...args: unknown[]): WorkflowParams;
  createWorkflowReport(...args: unknown[]): WorkflowReport;
  createTestReports(...args: unknown[]): Promise<TestReport[]>;
}

export const diffSec = (start: string | Date, end: string | Date): number => {
  const startDate = new Date(start);
  const endDate = new Date(end);

  return (endDate.getTime() - startDate.getTime()) / 1000;
};

export const secRound = (sec: number) => {
  const PRECISION = 3;
  return round(sec, PRECISION);
};

const reportTestCaseSchema = z
  .object({
    time: z.number().optional(),
    name: z.string().optional(),
    classname: z.string().optional(),
    assertions: z.number().optional(),
    failure: z.unknown().optional(),
    error: z.unknown().optional(),
    skipped: z.unknown().optional(),
  })
  .transform(({ failure, error, skipped, ...testCase }) => {
    return {
      ...testCase,
      successCount: failure || error || skipped ? 0 : 1,
      status: failure
        ? "FAILURE"
        : error
          ? "ERROR"
          : skipped
            ? "SKIPPED"
            : "SUCCESS",
    } as ReportTestCase;
  });

const reportTestSuiteSchema = z.object({
  testcase: z.array(reportTestCaseSchema).optional().default([]),
  tests: z.number().optional(),
  time: z.number().optional(),
  timestamp: z.coerce.date().optional(),
  skipped: z.number().optional(),
  failures: z.number().optional(),
  errors: z.number().optional(),
  name: z.string().optional(),
  disabled: z.number().optional(),
  hostname: z.string().optional(),
  id: z.string().optional(),
  package: z.string().optional(),
});

const reportTestSuitesSchema = z.object({
  testsuite: z.array(reportTestSuiteSchema).optional().default([]),
  failures: z.number().optional(),
  time: z.number().optional(),
  tests: z.number().optional(),
  name: z.string().optional(),
  errors: z.number().optional(),
  disabled: z.number().optional(),
});

export const convertToReportTestSuites = (
  testSuites: TestSuites,
): ReportTestSuites => {
  return reportTestSuitesSchema.parse(testSuites) as ReportTestSuites;
};

export const convertToTestReports = async (
  workflowReport: WorkflowReport,
  junitArtifacts: Artifact[],
): Promise<TestReport[]> => {
  const testReports: TestReport[] = [];
  for (const artifact of junitArtifacts) {
    const xmlString = Buffer.from(artifact.data).toString("utf8");
    try {
      const result = await parse(xmlString);
      if (!result) continue;

      const testSuites =
        "testsuite" in result
          ? result
          : {
              // Fill in testsuites property with testsuit values.
              testsuite: [result],
              name: workflowReport.workflowId,
              time: result.time,
              tests: result.tests,
              failures: result.failures,
              errors: result.errors,
            };

      testReports.push({
        workflowId: workflowReport.workflowId,
        workflowRunId: workflowReport.workflowRunId,
        buildNumber: workflowReport.buildNumber,
        workflowName: workflowReport.workflowName,
        createdAt: workflowReport.createdAt as Date, // NOTE: hack for types generated by protobuf
        branch: workflowReport.branch,
        service: workflowReport.service,
        testSuites: convertToReportTestSuites(testSuites),
        status:
          testSuites.failures && testSuites.failures > 0
            ? "FAILURE"
            : "SUCCESS",
        successCount: testSuites.failures && testSuites.failures > 0 ? 0 : 1,
      });
    } catch (error) {
      console.error(
        `Error: Could not parse as JUnit XML. workflowRunId: ${workflowReport.workflowRunId}, path: ${artifact.path}`,
      );
      console.error(error);
    }
  }
  return testReports;
};
