import { round } from "lodash-es";
import { type TestSuites, parse } from "junit2json";
import type { Assign } from "utility-types";
import { z } from "zod";
import type { Artifact } from "../client/client.js";
import type {
  PbWorkflowReport,
  PbWorkflowParams,
} from "../pb_types/workflow.js";

// Overwrite generated by protobuf types to more strict TypeScript types
export type Status = "SUCCESS" | "FAILURE" | "ABORTED" | "OTHER";
export type WorkflowReport = Assign<
  PbWorkflowReport,
  {
    status: Status;
    successCount: 0 | 1;
  }
>;
export type WorkflowParams = PbWorkflowParams;

const successCountSchema = z.union([z.literal(0), z.literal(1)]);
const testStatusSchema = z.enum(["SUCCESS", "FAILURE"]);
const testCaseStatusSchema = z.enum(["SUCCESS", "FAILURE", "ERROR", "SKIPPED"]);

type TestStatus = z.infer<typeof testStatusSchema>;
type TestCaseStatus = z.infer<typeof testCaseStatusSchema>;

const rawReportTestCaseSchema = z.object({
  time: z.number().optional(),
  name: z.string().optional(),
  classname: z.string().optional(),
  assertions: z.number().optional(),
  failure: z.unknown().optional(),
  error: z.unknown().optional(),
  skipped: z.unknown().optional(),
});

const reportTestCaseSchema = z.object({
  status: testCaseStatusSchema,
  successCount: successCountSchema,
  time: z.number().optional(),
  name: z.string().optional(),
  classname: z.string().optional(),
  assertions: z.number().optional(),
});
type ReportTestCase = z.infer<typeof reportTestCaseSchema>;

const rawReportTestSuiteSchema = z.object({
  testcase: z.array(rawReportTestCaseSchema).optional().default([]),
  tests: z.number().optional(),
  time: z.number().optional(),
  timestamp: z.coerce.date().optional(),
  skipped: z.number().optional(),
  failures: z.number().optional(),
  errors: z.number().optional(),
  name: z.string().optional(),
  disabled: z.number().optional(),
  hostname: z.string().optional(),
  id: z.string().optional(),
  package: z.string().optional(),
});

const reportTestSuiteSchema = z.object({
  testcase: z.array(reportTestCaseSchema).optional().default([]),
  tests: z.number().optional(),
  time: z.number().optional(),
  timestamp: z.coerce.date().optional(),
  skipped: z.number().optional(),
  failures: z.number().optional(),
  errors: z.number().optional(),
  name: z.string().optional(),
  disabled: z.number().optional(),
  hostname: z.string().optional(),
  id: z.string().optional(),
  package: z.string().optional(),
});
type ReportTestSuite = z.infer<typeof reportTestSuiteSchema>;

const rawReportTestSuitesSchema = z.object({
  testsuite: z.array(rawReportTestSuiteSchema).optional().default([]),
  failures: z.number().optional(),
  time: z.number().optional(),
  tests: z.number().optional(),
  name: z.string().optional(),
  errors: z.number().optional(),
  disabled: z.number().optional(),
});

const reportTestSuitesSchema = z.object({
  testsuite: z.array(reportTestSuiteSchema).optional().default([]),
  failures: z.number().optional(),
  time: z.number().optional(),
  tests: z.number().optional(),
  name: z.string().optional(),
  errors: z.number().optional(),
  disabled: z.number().optional(),
});
export type ReportTestSuites = z.infer<typeof reportTestSuitesSchema>;

const testReportSchema = z.object({
  workflowId: z.string(),
  workflowRunId: z.string(),
  buildNumber: z.number(),
  workflowName: z.string(),
  createdAt: z.date(),
  branch: z.string(),
  service: z.string(),
  testSuites: reportTestSuitesSchema,
  status: testStatusSchema,
  successCount: successCountSchema,
});
export type TestReport = z.infer<typeof testReportSchema>;

export interface Analyzer {
  createWorkflowParams(...args: unknown[]): WorkflowParams;
  createWorkflowReport(...args: unknown[]): WorkflowReport;
  createTestReports(...args: unknown[]): Promise<TestReport[]>;
}

export const diffSec = (start: string | Date, end: string | Date): number => {
  const startDate = new Date(start);
  const endDate = new Date(end);

  return (endDate.getTime() - startDate.getTime()) / 1000;
};

export const secRound = (sec: number) => {
  const PRECISION = 3;
  return round(sec, PRECISION);
};

const omitUndefinedValues = <T extends Record<string, unknown>>(
  record: T,
): Partial<T> => {
  return Object.fromEntries(
    Object.entries(record).filter(([, value]) => value !== undefined),
  ) as Partial<T>;
};

const calcSuccessCount = (
  hasProblem: unknown,
): z.infer<typeof successCountSchema> => {
  return hasProblem ? 0 : 1;
};

const calcTestCaseStatus = (
  failure: unknown,
  error: unknown,
  skipped: unknown,
): TestCaseStatus => {
  if (failure) return "FAILURE";
  if (error) return "ERROR";
  if (skipped) return "SKIPPED";
  return "SUCCESS";
};

const calcTestStatus = (failures: number | undefined): TestStatus => {
  return failures && failures > 0 ? "FAILURE" : "SUCCESS";
};

const sanitizeReportTestCase = (testCase: unknown): ReportTestCase => {
  const parsedTestCase = rawReportTestCaseSchema.parse(testCase);
  const status = calcTestCaseStatus(
    parsedTestCase.failure,
    parsedTestCase.error,
    parsedTestCase.skipped,
  );

  return reportTestCaseSchema.parse(
    omitUndefinedValues({
      time: parsedTestCase.time,
      name: parsedTestCase.name,
      classname: parsedTestCase.classname,
      assertions: parsedTestCase.assertions,
      successCount: calcSuccessCount(
        parsedTestCase.failure ||
          parsedTestCase.error ||
          parsedTestCase.skipped,
      ),
      status,
    }),
  );
};

const sanitizeReportTestSuite = (testSuite: unknown): ReportTestSuite => {
  const parsedTestSuite = rawReportTestSuiteSchema.parse(testSuite);

  return reportTestSuiteSchema.parse(
    omitUndefinedValues({
      testcase: parsedTestSuite.testcase.map(sanitizeReportTestCase),
      tests: parsedTestSuite.tests,
      time: parsedTestSuite.time,
      timestamp: parsedTestSuite.timestamp,
      skipped: parsedTestSuite.skipped,
      failures: parsedTestSuite.failures,
      errors: parsedTestSuite.errors,
      name: parsedTestSuite.name,
      disabled: parsedTestSuite.disabled,
      hostname: parsedTestSuite.hostname,
      id: parsedTestSuite.id,
      package: parsedTestSuite.package,
    }),
  );
};

export const convertToReportTestSuites = (
  testSuites: TestSuites,
): ReportTestSuites => {
  const parsedTestSuites = rawReportTestSuitesSchema.parse(testSuites);

  return reportTestSuitesSchema.parse(
    omitUndefinedValues({
      testsuite: parsedTestSuites.testsuite.map(sanitizeReportTestSuite),
      failures: parsedTestSuites.failures,
      time: parsedTestSuites.time,
      tests: parsedTestSuites.tests,
      name: parsedTestSuites.name,
      errors: parsedTestSuites.errors,
      disabled: parsedTestSuites.disabled,
    }),
  );
};

export const convertToTestReports = async (
  workflowReport: WorkflowReport,
  junitArtifacts: Artifact[],
): Promise<TestReport[]> => {
  const testReports: TestReport[] = [];
  for (const artifact of junitArtifacts) {
    const xmlString = Buffer.from(artifact.data).toString("utf8");
    try {
      const result = await parse(xmlString);
      if (!result) continue;

      const testSuites =
        "testsuite" in result
          ? result
          : {
              // Fill in testsuites property with testsuit values.
              testsuite: [result],
              name: workflowReport.workflowId,
              time: result.time,
              tests: result.tests,
              failures: result.failures,
              errors: result.errors,
            };
      const createdAt = z.date().parse(workflowReport.createdAt);
      const status = calcTestStatus(testSuites.failures);

      testReports.push(
        testReportSchema.parse({
          workflowId: workflowReport.workflowId,
          workflowRunId: workflowReport.workflowRunId,
          buildNumber: workflowReport.buildNumber,
          workflowName: workflowReport.workflowName,
          createdAt,
          branch: workflowReport.branch,
          service: workflowReport.service,
          testSuites: convertToReportTestSuites(testSuites),
          status,
          successCount: calcSuccessCount(
            testSuites.failures && testSuites.failures > 0,
          ),
        }),
      );
    } catch (error) {
      console.error(
        `Error: Could not parse as JUnit XML. workflowRunId: ${workflowReport.workflowRunId}, path: ${artifact.path}`,
      );
      console.error(error);
    }
  }
  return testReports;
};
