name: "CI"
on:
  push:
    paths-ignore:
      - "sample/**"
      - "**.md"
      - "renovate.json"
      - "Jenkinsfile"
permissions:
  contents: read

jobs:
  check_generated_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Since the version of earthly/actions-setup that supports the new GHA caches (v2) has not been released yet from v1.0.13,
      # we use a commit hash that already includes the support.
      # https://github.com/earthly/actions-setup/commit/b81a8e082d9fae6174210cfc6e54bd2feb124d94
      - uses: earthly/actions-setup@b81a8e082d9fae6174210cfc6e54bd2feb124d94
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate files
        run: |
          npm run proto
          npm run schema
      - name: Check uncommited generated files are exists
        run: git diff --exit-code

  lint_fmt:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Biome lint and format
        run: npm run biome:ci

  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      # Test
      - name: Type check
        run: npm run check
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci

      # Post actions
      - name: Create custom json
        env:
          JOB: ${{ github.job }}
          OS: ${{ runner.os }}
        run: |
          echo "{ \"job\": \"${JOB}\", \"node\": \"ubuntu-latest\", \"os\": \"${OS}\", \"container\": \"node:lts\" }" > custom_report.json
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test_results
          path: |
            junit/*.xml
            custom_report.json
      - uses: k1LoW/octocov-action@73d561f65d59e66899ed5c87e4621a913b5d5c20 # v1.5.0
        name: Upload coverage

  smoke_test:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    permissions:
      contents: read
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Build
        run: npm run build
      # Test
      - name: Smoke test bundled js
        run: |
          node --enable-source-maps dist/index.mjs --version
          node --enable-source-maps dist/index.mjs --help

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Since the version of earthly/actions-setup that supports the new GHA caches (v2) has not been released yet from v1.0.13,
      # we use a commit hash that already includes the support.
      # https://github.com/earthly/actions-setup/commit/b81a8e082d9fae6174210cfc6e54bd2feb124d94
      - uses: earthly/actions-setup@b81a8e082d9fae6174210cfc6e54bd2feb124d94
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: npm run docker
