name: "CI"
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Lint
        run: npm run lint
  
  build_and_test:
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: "node:lts"
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
