name: "CI"
on:
  push:
    paths-ignore:
    - 'sample/**'
    - '**.md'
    - 'renovate.json'
    - 'Jenkinsfile'

jobs:
  check_generated_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions-setup@v1
        with:
          version: latest
      - name: Generate files
        run: |
          npm run proto
          npm run schema
      - name: Check uncommited generated files are exists
        run: git diff --name-only --exit-code

  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci

      # Test
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci

      # Post actions
      - name: Create custom json
        env:
          JOB: ${{ github.job }}
          OS: ${{ runner.os }}
        run: |
          echo "{ \"job\": \"${JOB}\", \"node\": \"ubuntu-latest\", \"os\": \"${OS}\", \"container\": \"node:lts\" }" > custom_report.json
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test_results
          path: |
            junit/*.xml
            custom_report.json
      - uses: codecov/codecov-action@v3
        name: Upload coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions-setup@v1
        with:
          version: latest
      - name: Docker build
        run: npm run docker
