name: "CI"
on:
  push:
    paths-ignore:
      - "sample/**"
      - "**.md"
      - "renovate.json"
      - "Jenkinsfile"

jobs:
  check_generated_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1.0.13
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate files
        run: |
          npm run proto
          npm run schema
      - name: Check uncommited generated files are exists
        run: git diff --exit-code

  lint_fmt:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Biome lint and format
        run: npm run biome:ci

  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      # Test
      - name: Type check
        run: npm run check
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:ci

      # Post actions
      - name: Create custom json
        env:
          JOB: ${{ github.job }}
          OS: ${{ runner.os }}
        run: |
          echo "{ \"job\": \"${JOB}\", \"node\": \"ubuntu-latest\", \"os\": \"${OS}\", \"container\": \"node:lts\" }" > custom_report.json
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test_results
          path: |
            junit/*.xml
            custom_report.json
      - uses: k1LoW/octocov-action@1ad702b3118b6a055c00b01db68ca0d9f6641dbc # v1.4.0
        name: Upload coverage

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1.0.13
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: npm run docker
