name: "Publish docker image"
# on:
#   push:
#     branches:
#       - master
on: push

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    container:
      image: "docker"
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: echo ${DOCKER_PASSWORD} | docker login docker.pkg.github.com --username ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: kesin11
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        run: docker build -t docker.pkg.github.com/kesin11/ci_analyzer/ci_analyzer:latest .
        env:
          DOCKER_BUILDKIT: 1
      - name: docker push
        run: docker push docker.pkg.github.com/kesin11/ci_analyzer/ci_analyzer:latest
