name: "Docker build"

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  docker-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Since the version of earthly/actions-setup that supports the new GHA caches (v2) has not been released yet from v1.0.13,
      # we use a commit hash that already includes the support.
      # https://github.com/earthly/actions-setup/commit/b81a8e082d9fae6174210cfc6e54bd2feb124d94
      - uses: earthly/actions-setup@b81a8e082d9fae6174210cfc6e54bd2feb124d94
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        id: docker_meta
        with:
          images: ghcr.io/kesin11/ci_analyzer
          sep-tags: ","
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push latest tag
        run: |
          TAGS=$(echo "${{ steps.docker_meta.outputs.tags }}" | tr ',' ' ')
          earthly --strict --push --max-remote-cache \
            --remote-cache=ghcr.io/kesin11/ci_analyzer_earthly:cache \
            +docker-push \
            --TAGS "${TAGS}"
