name: "Docker build"

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: latest
      - uses: docker/metadata-action@v3
        id: docker_meta
        with:
          images: ghcr.io/kesin11/ci_analyzer
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push latest tag
        run: earthly --strict --push +docker

      - name: Copy latest tag to other tags
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/kesin11/ci_analyzer:latest
          dst: |
            ${{ steps.docker_meta.outputs.tags }}
