name: "Docker build"

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1.0.12
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: ghcr.io/kesin11/ci_analyzer
          sep-tags: ","
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push latest tag
        run: |
          TAGS=$(echo "${{ steps.docker_meta.outputs.tags }}" | tr ',' ' ')
          earthly --strict --push --max-remote-cache \
            --remote-cache=ghcr.io/kesin11/ci_analyzer_earthly:cache \
            +docker-push \
            --TAGS "${TAGS}"
