name: "Docker build"
on:
  push:
    paths-ignore:
    - 'sample/**'
    - '**.md'
    - 'renovate.json'
    - 'Jenkinsfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: "docker"
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ci_analyzer .
        env:
          DOCKER_BUILDKIT: 1
