name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Get next version
      - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: draft_release
    # We use PAT for release-drafter, because GITHUB_TOKEN does not trigger 'push tag' event for build Docker workflow
    # permissions:
    #   contents: write
    #   pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        with:
          publish: true
        env:
          # Workaround for trigger 'push tag' event for build Docker workflow
          # see: https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/4
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
