name: Ship js trigger
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          
      # - uses: actions/setup-node@v1
      #   with:
      #     registry-url: "https://registry.npmjs.org"
      # - run: |
      #     if [ -f "yarn.lock" ]; then
      #       yarn install
      #     else
      #       npm install
      #     fi
      
      # Make git tag and Github Releases
      - run: npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          # SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
